
server.port=10443
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=/etc/letsencrypt/live/backend.accessaligner.com/keystore.p12
server.ssl.key-store-password=3{z9!T3S%{2iGq5xC
server.ssl.key-alias=springboot

# Ensure messages are loaded as UTF-8
spring.messages.encoding=UTF-8

# Ensure the HTTP encoding is set to UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# Ensure that Tomcat uses UTF-8 for request and response encoding
server.tomcat.uri-encoding=UTF-8
server.tomcat.response-encoding=UTF-8


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.main.lazy-initialization=true
spring.servlet.multipart.max-file-size=100000000
spring.servlet.multipart.max-request-size=100000000
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
# Enable Gzip compression
server.compression.enabled=true
# Minimum response size (in bytes) to compress
#server.compression.min-response-size=2048  # 2 KB
# Specify the mime types to compress
server.compression.mime-types=text/html,text/plain,text/xml,text/css,text/javascript,application/javascript,application/json
# Optional: Set compression level (1-9)
server.compression.level=6


spring.datasource.url=jdbc:mysql://localhost:3306/accessaligner?createDatabaseIfNotExist=true
spring.datasource.username=db_access
spring.datasource.password=P@s$w0rd123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.web=DEBUG

#JWT Configuration
application.security.jwt.secret-key=7235753778214125442A472D4B6150645367566B59703373367639792F423F45
#30 day
application.security.jwt.expiration=2592000000
#180 day
application.security.jwt.refresh-token.expiration=15552000000 

#########
spring.mail.host=oxa.email
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=notification@accessaligner.com
spring.mail.password=LLzFV!v8y)z8
# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# TLS , port 587
#spring.mail.properties.mail.smtp.starttls.enable=true
# SSL, post 465
spring.mail.properties.mail.smtp.socketFactory.port = 465
spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory


spring.super.admin=Planification@accessaligner.com
spring.super.admin.password=123456